### PR TITLE
Removes IE8 support. Tests run fine in IE9.

### LINKED ISSUE #16: triggerHandler IE8 love
`// TODO needs IE8 support`

### LINKED ISSUE #27: event.data only allows strings in IE8
Related to the key already being used for something: http://msdn.microsoft.com/en-us/library/ie/cc288543(v=vs.85).aspx

This was working temporarily but regressed preventDefault support on #26 so had to be sacrificed.

### LINKED ISSUE #36: parent test failing in IE8
`equal( $children.eq(0).parent().length, 0);`

assigning to @johnbender per git blame

### LINKED ISSUE #39: stopImmediatePropagation on IE8

### LINKED ISSUE #41: IE8 custom event order with events bound to children/parents
See tests `events: .bind() bubbling custom event order (parent first)` and `events: .bind() bubbling custom event order (child first)`. Related: #40

### LINKED ISSUE #133: Remove IE8 support
This will lighten up the tablesaw jQuery-less package (that bundles shoestring) quite a bit.

Related, sign off on this would close:
* #41 
* #39 
* #36 
* #27 
* potentially #33 
* #16

### PR DESCRIPTION
**Pull request by zachleat**
One test still failing on Chrome and Firefox due to a previously failing and unrelated issue #35.

Fixes #133 
Fixes #41 
Fixes #39 
Fixes #36 
Fixes #27 
Fixes #16 

We’ll probably want to bump to 2.0 when we release this.

Benefit: tablesaw non-jQuery version JavaScript that bundles shoestring saves about 1KB of GZIP size.

Before:
image

After:
image

### CODE REVIEW

**Comment by johnbender** [comment]
👍

File: dist/shoestring-dev.js [hunk 1]
```diff
@@ -443,25 +443,13 @@
...
-			return win.attachEvent( "on" + evt, cb );
-		};
-	}
-
 	// If DOM is already ready at exec time, depends on the browser.
 	// From: https://github.com/mobify/mobifyjs/blob/526841be5509e28fc949038021799e4223479f8d/src/capture.js#L128
-	if (doc.attachEvent ? doc.readyState === "complete" : doc.readyState !== "loading") {
+	if (doc.readyState !== "loading") {
 		runReady();
 	}	else {
```
Comment (johnbender) [inline dist/shoestring-dev.js]: whitespace
